#!/usr/bin/env python
# -*-encoding: utf-8 -*-
"""
电商会员营销分析,根据电商会员营销组数据需求，从CRM提取数据,生成相应Excel表格，
然后通过公司邮箱发送到电商会员营销组邮箱中
"""
import pandas as pd
import os
import pymysql
import datetime


# import smtplib
# from email.mime.multipart import MIMEMultipart
# from email.mime.text import MIMEText
# from email.mime.application import MIMEApplication


# 获得当天时间标准格式
def now_date():
    dt = datetime.datetime.now()
    return dt.strftime("%Y-%m-%d")


# 获得当天分析后数据,根据生成表单名获得数据
def get_document(data_name):
    conn = pymysql.connect(host="192.168.111.251", user="root", passwd="P#y20bsy17", db="tag_text", charset="utf8")
    sql = "select * from member_repurchase_analysis_"+ data_name
    document = pd.read_sql(sql, conn)
    return document


# 将文档数据转化成Excel文档，并规范命名后导出到目标路径
def data_output(document, data_name, targedir):
    os.chdir(targedir)
    try:
        temp_path = os.getcwd()
        if temp_path == targedir:
            print("工作路径已经指向目标路径!")
    except: print("工作路径未改变!")
    if "day" in data_name:
        name = "会员交易数据分析_日度_" + now_date() + ".xlsx"
        document.to_excel(name, index=False)
    elif "month" in data_name:
        name = "会员交易数据分析_月度_" + now_date () + ".xlsx"
        document.to_excel (name, index=False)
    elif "shop" in data_name:
        name = "会员交易数据分析_日度BY店铺_" + now_date () + ".xlsx"
        document.to_excel (name, index=False)
    else:print("无此文档")
    return print("%s成功导出",data_name)


# 从工作路径中获取全部文档，并通过潘颖的邮箱发送给到目标方
# def send_mail(file_dir, file_name):
#     sender = 'panying@besunyen.com'
#     my_pass = 'panying199052'
#     receivers = ['1298247841@qq.com']  # 接收邮件，可设置为你的QQ邮箱或者其他邮箱
#     # 创建一个带附件的实例
#     message = MIMEMultipart()
#     message['From'] = Header("电商每日拉新监控", 'utf-8')
#     message['To'] = Header("测试", 'utf-8')
#     subject = '电商每日拉新监控 邮件测试'
#     message['Subject'] = Header(subject, 'utf-8')
#     # 邮件正文内容
#     message.attach(MIMEText('这是信息中心-潘颖邮箱 发送测试邮件……', 'plain', 'utf-8'))
#
#     # 构造附件1，传送当前工作目录下的 test.t 文件
#     xlsxpart = MIMEApplication (open ('test.xlsx', 'rb').read ())
#     xlsxpart.add_header ('Content-Disposition', 'attachment', filename='test.xlsx')
#     msg.attach (xlsxpart)
#     # 这里的filename可以任意写，写什么名字，邮件中显示什么名字
#     att1["Content-Disposition"] = 'attachment; filename="test.txt"'
#     message.attach (att1)
#
#     # 构造附件2，传送当前目录下的 runoob.txt 文件
#     att2 = MIMEText (open ('runoob.txt', 'rb').read (), 'base64', 'utf-8')
#     att2["Content-Type"] = 'application/octet-stream'
#     att2["Content-Disposition"] = 'attachment; filename="runoob.txt"'
#     message.attach (att2)
#
#     try:
#         smtpObj = smtplib.SMTP ('localhost')
#         smtpObj.sendmail (sender, receivers, message.as_string ())
#         print
#         "邮件发送成功"
#     except smtplib.SMTPException:
#         print
#         "Error: 无法发送邮件"


# 将当日生成的文档转移至历史数据中

# 主函数
if __name__ == '__main__':
    targetdir = "V:\\【需求】电商数据需求\\会员营销分析"
    dataname = ["shop", "day", "month"]
    for i in range(0, 3):
        data_name = dataname[i]
        document = get_document(data_name)
        data_output(document, data_name, targetdir)


